name: main file

on: [push]

jobs:
  job1:
    uses: Shiv-Ranjani/GITActions/.github/workflows/helloworld.yaml@main
  job2:
    runs-on: ubuntu_latest
    steps: 
      - name: create string
        run: |
          MY_STRING="hello world"
          echo "::set-output name=content::$MY_STRING"
      
    
    
  
 
    

